services:
  app:
    image: igor0670/portable-jukebox:latest
    container_name: portable-jukebox-app
    env_file: .env
    volumes:
      - ./downloads:/downloads
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: portable-jukebox-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 portable-jukebox-app
    restart: unless-stopped
