services:
  app:
    image: igor0670/portable-jukebox:latest
    container_name: portable-jukebox-app
    env_file: .env
    volumes:
      - ./downloads:/downloads
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

